### PR TITLE
增加多进程情况下，ssh连接客户端

### PR DESCRIPTION
**Pull request by stevenfeixue**

### CODE REVIEW

**Comment by CMGS** [comment]
如果我是你就会抽象出一个 ssh_client 函数复用……你看这有重复啊

**Comment by stevenfeixue** [comment]
我一开始想法是把xxx_clients干掉的 = =

**Comment by CMGS** [comment]
doit

On Wed, Jan 27, 2016 at 5:39 PM, Fei Xue notifications@github.com wrote:

> 我一开始想法是把xxx_clients干掉的 = =
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/projecteru/eru-armin/pull/1#issuecomment-175512247.

## 

-CMGS
A simple coder.
Love travel, sports especially outdoor sports and computer technology.
Have a dream that one day can tour around.

**Comment by stevenfeixue** [comment]
我还是抽ssh_client吧

**Pull request merged**
